export const BLOTTER_LIST_REQUEST = 'BLOTTER_LIST_REQUEST'
export const BLOTTER_LIST_SUCCESS = 'BLOTTER_LIST_SUCCESS'
export const BLOTTER_LIST_FAIL = 'BLOTTER_LIST_FAIL'

export const BLOTTER_DETAILS_REQUEST = 'BLOTTER_DETAILS_REQUEST'
export const BLOTTER_DETAILS_SUCCESS = 'BLOTTER_DETAILS_SUCCESS'
export const BLOTTER_DETAILS_FAIL = 'BLOTTER_DETAILS_FAIL'

export const BLOTTER_DELETE_REQUEST = 'BLOTTER_DELETE_REQUEST'
export const BLOTTER_DELETE_SUCCESS = 'BLOTTER_DELETE_SUCCESS'
export const BLOTTER_DELETE_FAIL = 'BLOTTER_DELETE_FAIL'

export const BLOTTER_CREATE_REQUEST = 'BLOTTER_CREATE_REQUEST'
export const BLOTTER_CREATE_SUCCESS = 'BLOTTER_CREATE_SUCCESS'
export const BLOTTER_CREATE_FAIL = 'BLOTTER_CREATE_FAIL'
export const BLOTTER_CREATE_RESET = 'BLOTTER_CREATE_RESET'

export const BLOTTER_UPDATE_REQUEST = 'BLOTTER_UPDATE_REQUEST'
export const BLOTTER_UPDATE_SUCCESS = 'BLOTTER_UPDATE_SUCCESS'
export const BLOTTER_UPDATE_FAIL = 'BLOTTER_UPDATE_FAIL'
export const BLOTTER_UPDATE_RESET = 'BLOTTER_UPDATE_RESET'
