export const RESIDENT_LIST_REQUEST = 'RESIDENT_LIST_REQUEST'
export const RESIDENT_LIST_SUCCESS = 'RESIDENT_LIST_SUCCESS'
export const RESIDENT_LIST_FAIL = 'RESIDENT_LIST_FAIL'

export const RESIDENT_DETAILS_REQUEST = 'RESIDENT_DETAILS_REQUEST'
export const RESIDENT_DETAILS_SUCCESS = 'RESIDENT_DETAILS_SUCCESS'
export const RESIDENT_DETAILS_FAIL = 'RESIDENT_DETAILS_FAIL'

export const RESIDENT_DELETE_REQUEST = 'RESIDENT_DELETE_REQUEST'
export const RESIDENT_DELETE_SUCCESS = 'RESIDENT_DELETE_SUCCESS'
export const RESIDENT_DELETE_FAIL = 'RESIDENT_DELETE_FAIL'

export const RESIDENT_CREATE_REQUEST = 'RESIDENT_CREATE_REQUEST'
export const RESIDENT_CREATE_SUCCESS = 'RESIDENT_CREATE_SUCCESS'
export const RESIDENT_CREATE_FAIL = 'RESIDENT_CREATE_FAIL'
export const RESIDENT_CREATE_RESET = 'RESIDENT_CREATE_RESET'

export const RESIDENT_UPDATE_REQUEST = 'RESIDENT_UPDATE_REQUEST'
export const RESIDENT_UPDATE_SUCCESS = 'RESIDENT_UPDATE_SUCCESS'
export const RESIDENT_UPDATE_FAIL = 'RESIDENT_UPDATE_FAIL'
export const RESIDENT_UPDATE_RESET = 'RESIDENT_UPDATE_RESET'
