const residents = [
  {
    _id: '1',
    firstName: 'Mat',
    lastName: 'Fajutagana',
    middleName: 'Rioflorido',
    image: '/image/mat.jpg',
    age: 24,
    birthDay: '08/17/1996',
    sex: 'M',
    phoneNumber: '09177724647',
    address: 'Brgy Calingag, Pinamalayan Oriental Mindoro',
  },
  {
    _id: '2',
    firstName: 'Aira Elene',
    lastName: 'Sedaria',
    middleName: 'Amar',
    image: '/image/aira.jpg',
    age: 23,
    birthDay: '08/06/1997',
    sex: 'F',
    phoneNumber: '09177724648',
    address: 'Brgy Calingag, Pinamalayan Oriental Mindoro',
  },
  {
    _id: '3',
    firstName: 'Kent Lawrence',
    lastName: 'Liwanagan',
    middleName: 'Enriquez',
    image: '/image/kent.jpg',
    age: 20,
    birthDay: '08/06/2001',
    sex: 'F',
    phoneNumber: '09177724578',
    address: 'Brgy Calingag, Pinamalayan Oriental Mindoro',
  },
  {
    _id: '4',
    firstName: 'Kent Lawrence',
    lastName: 'Liwanagan',
    middleName: 'Enriquez',
    image: '/image/kent.jpg',
    age: 20,
    birthDay: '08/06/2001',
    sex: 'F',
    phoneNumber: '09177724578',
  },
  {
    _id: '5',
    firstName: 'Kent Lawrence',
    lastName: 'Liwanagan',
    middleName: 'Enriquez',
    image: '/image/kent.jpg',
    age: 20,
    birthDay: '08/06/2001',
    sex: 'F',
    phoneNumber: '09177724578',
  },

  {
    _id: '6',
    firstName: 'Kent Lawrence',
    lastName: 'Liwanagan',
    middleName: 'Enriquez',
    image: '/image/kent.jpg',
    age: 20,
    birthDay: '08/06/2001',
    sex: 'F',
    phoneNumber: '09177724578',
  },
  {
    _id: '7',
    firstName: 'Kent Lawrence',
    lastName: 'Liwanagan',
    middleName: 'Enriquez',
    image: '/image/kent.jpg',
    age: 20,
    birthDay: '08/06/2001',
    sex: 'F',
    phoneNumber: '09177724578',
  },
  {
    _id: '8',
    firstName: 'Kent Lawrence',
    lastName: 'Liwanagan',
    middleName: 'Enriquez',
    image: '/image/kent.jpg',
    age: 20,
    birthDay: '08/06/2001',
    sex: 'F',
    phoneNumber: '09177724578',
  },
  {
    _id: '9',
    firstName: 'Kent Lawrence',
    lastName: 'Liwanagan',
    middleName: 'Enriquez',
    image: '/image/kent.jpg',
    age: 20,
    birthDay: '08/06/2001',
    sex: 'F',
    phoneNumber: '09177724578',
  },
  {
    _id: '10',
    firstName: 'Kent Lawrence',
    lastName: 'Liwanagan',
    middleName: 'Enriquez',
    image: '/image/kent.jpg',
    age: 20,
    birthDay: '08/06/2001',
    sex: 'F',
    phoneNumber: '09177724578',
  },
  {
    _id: '11',
    firstName: 'Kent Lawrence',
    lastName: 'Liwanagan',
    middleName: 'Enriquez',
    image: '/image/kent.jpg',
    age: 20,
    birthDay: '08/06/2001',
    sex: 'F',
    phoneNumber: '09177724578',
  },
  {
    _id: '12',
    firstName: 'Kent Lawrence',
    lastName: 'Liwanagan',
    middleName: 'Enriquez',
    image: '/image/kent.jpg',
    age: 20,
    birthDay: '08/06/2001',
    sex: 'F',
    phoneNumber: '09177724578',
  },
  {
    _id: '13',
    firstName: 'Kent Lawrence',
    lastName: 'Liwanagan',
    middleName: 'Enriquez',
    image: '/image/kent.jpg',
    age: 20,
    birthDay: '08/06/2001',
    sex: 'F',
    phoneNumber: '09177724578',
  },
  {
    _id: '14',
    firstName: 'Kent Lawrence',
    lastName: 'Liwanagan',
    middleName: 'Enriquez',
    image: '/image/kent.jpg',
    age: 20,
    birthDay: '08/06/2001',
    sex: 'F',
    phoneNumber: '09177724578',
  },
  {
    _id: '15',
    firstName: 'Kent Lawrence',
    lastName: 'Liwanagan',
    middleName: 'Enriquez',
    image: '/image/kent.jpg',
    age: 20,
    birthDay: '08/06/2001',
    sex: 'F',
    phoneNumber: '09177724578',
  },
  {
    _id: '16',
    firstName: 'Kent Lawrence',
    lastName: 'Liwanagan',
    middleName: 'Enriquez',
    image: '/image/kent.jpg',
    age: 20,
    birthDay: '08/06/2001',
    sex: 'F',
    phoneNumber: '09177724578',
  },
  {
    _id: '17',
    firstName: 'Kent Lawrence',
    lastName: 'Liwanagan',
    middleName: 'Enriquez',
    image: '/image/kent.jpg',
    age: 20,
    birthDay: '08/06/2001',
    sex: 'F',
    phoneNumber: '09177724578',
  },
  {
    _id: '18',
    firstName: 'Jeraldine',
    lastName: 'Dasco',
    middleName: 'Lala',
    image: '/image/kent.jpg',
    age: 20,
    birthDay: '08/06/2001',
    sex: 'F',
    phoneNumber: '09177724578',
  },
]

export default residents
